Used new fperms library
druids/django-fperms-iscore pull request #8
Opened 2020-09-17 17:45 UTC by matllubos

2020-09-21 11:46 UTC, rubickcz requested changes

2020-09-21 11:46 UTC, rubickcz commented on example/dj/apps/issue_tracker/tests/ui_permissions.py
> +        # assert_http_redirect(resp)
Pls remove this commented code or uncomment it.

2020-09-21 11:46 UTC, rubickcz commented on fperms_iscore/forms.py
> +    return max(0, 0, *values)
I had to google why you used twice the zero value, but this is the shortest solution, that's true :(

2020-09-21 11:46 UTC, rubickcz commented on fperms_iscore/locale/cs/LC_MESSAGES/django.po
> +msgstr "podskupiiny"
podskupiny

2020-09-22 10:54 UTC, rubickcz approved these changes

2020-09-24 08:06 UTC, Formulka approved these changes

2020-09-24 12:28 UTC, merged